### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by lighttiger2505** [comment]
@mattn thanks for contribution.

but your commit is not fix build. Could you tell me why you need to fix this?

```
/tmp/go-build513997367/github.com/lighttiger2505/lab/gitlab/_test/_obj_test/client.go:55:2: cannot use jobs (type []gitlab.Job) as type []*gitlab.Job in return argument
```

https://travis-ci.org/lighttiger2505/lab/builds/369107323?utm_source=github_status&utm_medium=notification

**Comment by lighttiger2505** [comment]
The result of building your branch on my machine is as follows

$ go build ./...
# github.com/mattn/lab/gitlab
gitlab/client.go:47:2: cannot use jobs (type []gitlab.Job) as type []*gitlab.Job in return argument
# github.com/mattn/lab/commands
commands/pipeline.go:126:45: cannot use jobs (type []"github.com/mattn/lab/vendor/github.com/xanzy/go-gitlab".Job) as type []*"github.com/mattn/lab/vendor/github.com/xanzy/go-gitlab".Job in argument to jobOutput

**Comment by mattn** [comment]
Ah, sorry. In my local repository, go-gitlab is master branch. And I built lab with `go build`. It seems that go-gitlab add breaking changes at https://github.com/xanzy/go-gitlab/pull/364 . So please close this PR.

**Comment by lighttiger2505** [comment]
@mattn Understood. I am happy to receive a pull request from a respecting person.

**Comment by mattn** [comment]
FYI, v0.9.0 is tagged in go-gitlab just now.

**Comment by lighttiger2505** [comment]
Thank you for teaching me.

Since I upgraded go-gitlab, I will merge your pull request.

**Pull request merged**
